/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR42_GPIO_MUX3_GPIO_SEL_LOW_MASK 0x18U /*!< GPIO3 and CM7_GPIO3 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR43_GPIO_MUX3_GPIO_SEL_HIGH_MASK 0x8000U /*!< GPIO3 and CM7_GPIO3 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_RXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_TXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_TXD_SIGNAL                                    TXD   /*!< Signal name */

/* GPIO_LPSR_01 (coord R6), CAN3_RX/U42[4] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN3_RX_PERIPHERAL                                   CAN3   /*!< Peripheral name */
#define BOARD_INITPINS_CAN3_RX_SIGNAL                                         RX   /*!< Signal name */

/* GPIO_LPSR_00 (coord N6), CAN3_TX/U42[1] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN3_TX_PERIPHERAL                                   CAN3   /*!< Peripheral name */
#define BOARD_INITPINS_CAN3_TX_SIGNAL                                         TX   /*!< Signal name */

/* GPIO_AD_01 (coord R14), SIM1_CLK/J44[C3]/J57[7]/CTP_RST_B/J48[28]/J10[4]/J25[13] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN2_RX_PERIPHERAL                                   CAN2   /*!< Peripheral name */
#define BOARD_INITPINS_CAN2_RX_SIGNAL                                         RX   /*!< Signal name */

/* GPIO_AD_00 (coord N12), SIM1_TRXD/J44[C7]/J57[9]/CTP_INT/J48[29]/J25[15]/J9[14] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN2_TX_PERIPHERAL                                   CAN2   /*!< Peripheral name */
#define BOARD_INITPINS_CAN2_TX_SIGNAL                                         TX   /*!< Signal name */

/* GPIO_AD_02 (coord R13), RS485_UART_TX / BLUETOOTH_UART_TX */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART8_TX_PERIPHERAL                             LPUART8   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART8_TX_SIGNAL                                     TXD   /*!< Signal name */

/* GPIO_AD_03 (coord P15), RS485_UART_RX / BLUETOOTH_UART_RX */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART8_RX_PERIPHERAL                             LPUART8   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART8_RX_SIGNAL                                     RXD   /*!< Signal name */

/* GPIO_LPSR_07 (coord R8), I2C6_SCL/J50[12] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C6_SCL_PERIPHERAL                                LPI2C6   /*!< Peripheral name */
#define BOARD_INITPINS_I2C6_SCL_SIGNAL                                       SCL   /*!< Signal name */

/* GPIO_LPSR_06 (coord P8), I2C6_SDA/J50[11] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C6_SDA_PERIPHERAL                                LPI2C6   /*!< Peripheral name */
#define BOARD_INITPINS_I2C6_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_DISP_B1_01 (coord D13), ENET_RGMII_RXC/U10[27] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_RX_CLK_PERIPHERAL                       ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_RX_CLK_SIGNAL                        enet_rx_clk   /*!< Signal name */

/* GPIO_DISP_B1_04 (coord E10), ENET_RGMII_RXD2/U10[23] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_RXD2_PERIPHERAL                         ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_RXD2_SIGNAL                           enet_rdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_QOS_RXD2_CHANNEL                                  2U   /*!< Signal channel */

/* GPIO_DISP_B1_05 (coord C11), ENET_RGMII_RXD3/U10[22] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_RXD3_PERIPHERAL                         ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_RXD3_SIGNAL                           enet_rdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_QOS_RXD3_CHANNEL                                  3U   /*!< Signal channel */

/* GPIO_DISP_B1_06 (coord D10), ENET_RGMII_TXD3/U10[15]/BT_CFG[0] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_TXD3_PERIPHERAL                         ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_TXD3_SIGNAL                           enet_tdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_QOS_TXD3_CHANNEL                                  3U   /*!< Signal channel */

/* GPIO_DISP_B1_07 (coord E12), ENET_RGMII_TXD2/U10[16]/BT_CFG[1] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_TXD2_PERIPHERAL                         ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_TXD2_SIGNAL                           enet_tdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_QOS_TXD2_CHANNEL                                  2U   /*!< Signal channel */

/* GPIO_EMC_B1_09 (coord A3), SEMC_A0/U13[23]/U25[23] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A0_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A0_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A0_CHANNEL                                        0U   /*!< Signal channel */

/* GPIO_EMC_B1_10 (coord A2), SEMC_A1/U13[24]/U25[24] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A1_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A1_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A1_CHANNEL                                        1U   /*!< Signal channel */

/* GPIO_EMC_B1_11 (coord C2), SEMC_A2/U13[25]/U25[25] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A2_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A2_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A2_CHANNEL                                        2U   /*!< Signal channel */

/* GPIO_EMC_B1_12 (coord C5), SEMC_A3/U13[26]/U25[26] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A3_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A3_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A3_CHANNEL                                        3U   /*!< Signal channel */

/* GPIO_EMC_B1_13 (coord D5), SEMC_A4/U13[29]/U25[29] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A4_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A4_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A4_CHANNEL                                        4U   /*!< Signal channel */

/* GPIO_EMC_B1_14 (coord B1), SEMC_A5/U13[30]/U25[30] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A5_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A5_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A5_CHANNEL                                        5U   /*!< Signal channel */

/* GPIO_EMC_B1_15 (coord C1), SEMC_A6/U13[31]/U25[31] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A6_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A6_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A6_CHANNEL                                        6U   /*!< Signal channel */

/* GPIO_EMC_B1_16 (coord D3), SEMC_A7/U13[32]/U25[32] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A7_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A7_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A7_CHANNEL                                        7U   /*!< Signal channel */

/* GPIO_EMC_B1_17 (coord B3), SEMC_A8/U13[33]/U25[33] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A8_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A8_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A8_CHANNEL                                        8U   /*!< Signal channel */

/* GPIO_EMC_B1_18 (coord B4), SEMC_A9/U13[34]/U25[34]/U14A[D5] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A9_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A9_SIGNAL                                       ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A9_CHANNEL                                        9U   /*!< Signal channel */

/* GPIO_EMC_B1_23 (coord B2), SEMC_A10/U13[22]/U25[22] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A10_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A10_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A10_CHANNEL                                      10U   /*!< Signal channel */

/* GPIO_EMC_B1_19 (coord C4), SEMC_A11/U13[35]/U25[35]/U14A[C7] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A11_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A11_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A11_CHANNEL                                      11U   /*!< Signal channel */

/* GPIO_EMC_B1_20 (coord C3), SEMC_A12/U13[36]/U25[36]/U14A[D4] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A12_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A12_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A12_CHANNEL                                      12U   /*!< Signal channel */

/* GPIO_EMC_B1_00 (coord F3), SEMC_D0/U13[2] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D0_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D0_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D0_CHANNEL                                        0U   /*!< Signal channel */

/* GPIO_EMC_B1_01 (coord F2), SEMC_D1/U13[4]/U14A[J4] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D1_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D1_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D1_CHANNEL                                        1U   /*!< Signal channel */

/* GPIO_EMC_B1_02 (coord G4), SEMC_D2/U13[5] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D2_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D2_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D2_CHANNEL                                        2U   /*!< Signal channel */

/* GPIO_EMC_B1_03 (coord E4), SEMC_D3/U13[7] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D3_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D3_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D3_CHANNEL                                        3U   /*!< Signal channel */

/* GPIO_EMC_B1_04 (coord H5), SEMC_D4/U13[8] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D4_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D4_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D4_CHANNEL                                        4U   /*!< Signal channel */

/* GPIO_EMC_B1_05 (coord F4), SEMC_D5/U13[10] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D5_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D5_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D5_CHANNEL                                        5U   /*!< Signal channel */

/* GPIO_EMC_B1_06 (coord H4), SEMC_D6/U13[11] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D6_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D6_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D6_CHANNEL                                        6U   /*!< Signal channel */

/* GPIO_EMC_B1_07 (coord H3), SEMC_D7/U13[13] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D7_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D7_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D7_CHANNEL                                        7U   /*!< Signal channel */

/* GPIO_EMC_B1_30 (coord E3), SEMC_D8/U13[42] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D8_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D8_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D8_CHANNEL                                        8U   /*!< Signal channel */

/* GPIO_EMC_B1_31 (coord D2), SEMC_D9/U13[44] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D9_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D9_SIGNAL                                       DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D9_CHANNEL                                        9U   /*!< Signal channel */

/* GPIO_EMC_B1_32 (coord D1), SEMC_D10/U13[45] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D10_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D10_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D10_CHANNEL                                      10U   /*!< Signal channel */

/* GPIO_EMC_B1_33 (coord E2), SEMC_D11/U13[47] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D11_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D11_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D11_CHANNEL                                      11U   /*!< Signal channel */

/* GPIO_EMC_B1_34 (coord E1), SEMC_D12/U13[48] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D12_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D12_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D12_CHANNEL                                      12U   /*!< Signal channel */

/* GPIO_EMC_B1_35 (coord F1), SEMC_D13/U13[50] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D13_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D13_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D13_CHANNEL                                      13U   /*!< Signal channel */

/* GPIO_EMC_B1_36 (coord G1), SEMC_D14/U13[51] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D14_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D14_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D14_CHANNEL                                      14U   /*!< Signal channel */

/* GPIO_EMC_B1_38 (coord J1), SEMC_DM1/U13[39] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM1_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM1_SIGNAL                                        DM   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DM1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_B1_08 (coord F5), SEMC_DM0/U13[15] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM0_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM0_SIGNAL                                        DM   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DM0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_B1_24 (coord J5), SEMC_CAS/U13[17]/U25[17] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CAS_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CAS_SIGNAL                                  semc_cas   /*!< Signal name */

/* GPIO_EMC_B1_21 (coord G2), SEMC_BA0/U13[20]/U25[20] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_BA0_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_BA0_SIGNAL                                        BA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_BA0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_B1_22 (coord H2), SEMC_BA1/U13[21]/U25[21]/U14A[C4] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_BA1_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_BA1_SIGNAL                                        BA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_BA1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_B1_25 (coord J4), SEMC_RAS/U13[18]/U25[18] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_RAS_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_RAS_SIGNAL                                  semc_ras   /*!< Signal name */

/* GPIO_EMC_B1_27 (coord G5), SEMC_CKE/U13[37]/U25[37] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CKE_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CKE_SIGNAL                                  semc_cke   /*!< Signal name */

/* GPIO_EMC_B1_28 (coord E5), SEMC_WE/U13[16]/U25[16] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_WE_PERIPHERAL                                   SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_WE_SIGNAL                                    semc_we   /*!< Signal name */

/* GPIO_EMC_B1_37 (coord H1), SEMC_D15/U13[53] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D15_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D15_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D15_CHANNEL                                      15U   /*!< Signal channel */

/* GPIO_AD_31 (coord J17), LPSPI1_SDI/U27[2]/J10[10] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SIN_PERIPHERAL                              LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SIN_SIGNAL                                     SIN   /*!< Signal name */

/* GPIO_AD_30 (coord K17), LPSPI1_SDO/U27[5]/J10[8]/Backlight_CTL/J48[34]/U46[4] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SOUT_PERIPHERAL                             LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SOUT_SIGNAL                                   SOUT   /*!< Signal name */

/* GPIO_AD_08 (coord R15), USB_OTG2_ID/U20[3]/U18[A1]/J26[12]/J18[4] */
/* Routed pin properties */
#define BOARD_INITPINS_USB2_ID_PERIPHERAL                                   USB2   /*!< Peripheral name */
#define BOARD_INITPINS_USB2_ID_SIGNAL                                usb2_otg_id   /*!< Signal name */

/* GPIO_AD_06 (coord N13), USB_OTG2_OC/U18[A2]/J9[10]/AUD_INT */
/* Routed pin properties */
#define BOARD_INITPINS_USB2_OC_PERIPHERAL                                   USB2   /*!< Peripheral name */
#define BOARD_INITPINS_USB2_OC_SIGNAL                                usb_otg2_oc   /*!< Signal name */

/* GPIO_AD_07 (coord T17), USB_OTG2_PWR/WL_DEV_WAKE/U354[10]/J10[2] */
/* Routed pin properties */
#define BOARD_INITPINS_USB2_PWR_PERIPHERAL                                  USB2   /*!< Peripheral name */
#define BOARD_INITPINS_USB2_PWR_SIGNAL                              usb_otg2_pwr   /*!< Signal name */

/* GPIO_AD_09 (coord R16), USB_OTG1_ID/U28[3]/U26[A1]/J26[10]/J20[4] */
/* Routed pin properties */
#define BOARD_INITPINS_USB1_ID_PERIPHERAL                                   USB1   /*!< Peripheral name */
#define BOARD_INITPINS_USB1_ID_SIGNAL                                usb1_otg_id   /*!< Signal name */

/* GPIO_AD_11 (coord P16), USB_OTG1_OC/U26[A2]/J26[4] */
/* Routed pin properties */
#define BOARD_INITPINS_USB1_OC_PERIPHERAL                                   USB1   /*!< Peripheral name */
#define BOARD_INITPINS_USB1_OC_SIGNAL                                usb_otg1_oc   /*!< Signal name */

/* GPIO_EMC_B1_26 (coord J3), SEMC_CLK/U13[38]/U25[38] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CLK_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CLK_SIGNAL                                  semc_clk   /*!< Signal name */

/* GPIO_EMC_B1_29 (coord E6), SEMC_CS0/U13[19]/U25[19] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CS0_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CS0_SIGNAL                                        CS   /*!< Signal name */
#define BOARD_INITPINS_SEMC_CS0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_SD_B2_05 (coord E14), FlexSPI_A_DQS/U21[C3] */
/* Routed pin properties */
#define BOARD_INITPINS_SDHC2_CMD_PERIPHERAL                             FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_SDHC2_CMD_SIGNAL                            FLEXSPI_A_DQS   /*!< Signal name */

/* GPIO_AD_34 (coord J16), 1588_EVENT0_IN/SD1_VSELECT */
/* Routed pin properties */
#define BOARD_INITPINS_SDHC1_VSELECT_PERIPHERAL                           USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SDHC1_VSELECT_SIGNAL                        usdhc_vselect   /*!< Signal name */

/* GPIO_SD_B1_00 (coord B16), SD1_CMD/J15[3]/WIFI_SDIO_CMD/J54[11]/NVCC_SD/U19G[D14] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_CMD_PERIPHERAL                                 USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_CMD_SIGNAL                                  usdhc_cmd   /*!< Signal name */

/* GPIO_SD_B1_01 (coord D15), SD1_CLK/J15[5]/WIFI_SDIO_CLK/J54[9] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_CLK_PERIPHERAL                                 USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_CLK_SIGNAL                                  usdhc_clk   /*!< Signal name */

/* GPIO_SD_B1_02 (coord C15), SD1_D0/J15[7]/WIFI_SDIO_D0/J54[13]/NVCC_SD/U19G[D14] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D0_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D0_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D0_CHANNEL                                         0U   /*!< Signal channel */

/* GPIO_SD_B1_03 (coord B17), SD1_D1/J15[8]/WIFI_SDIO_D1/J54[15] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D1_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D1_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D1_CHANNEL                                         1U   /*!< Signal channel */

/* GPIO_SD_B1_04 (coord B15), SD1_D2/J15[1]/WIFI_SDIO_D2/J54[17] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D2_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D2_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D2_CHANNEL                                         2U   /*!< Signal channel */

/* GPIO_SD_B1_05 (coord A16), SD1_D3/J15[2]/WIFI_SDIO_D3/J54[19] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D3_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D3_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D3_CHANNEL                                         3U   /*!< Signal channel */

/* GPIO_AD_12 (coord P17), SPDIF_LOCK/J26[6]/ENET_INT/U7[21] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_RST_PERIPHERAL                                  GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_RST_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADC_RST_CHANNEL                                       11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADC_RST_GPIO                                        GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADC_RST_GPIO_PIN                                      11U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADC_RST_GPIO_PIN_MASK                         (1U << 11U)   /*!< GPIO pin mask */

/* GPIO_AD_13 (coord L12), SPDIF_SR_CLK/ANATOP_32K_OUT/J26[8] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_SYNC_PERIPHERAL                                 GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_SYNC_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADC_SYNC_CHANNEL                                      12U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADC_SYNC_GPIO                                       GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADC_SYNC_GPIO_PIN                                     12U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADC_SYNC_GPIO_PIN_MASK                        (1U << 12U)   /*!< GPIO pin mask */

/* GPIO_AD_14 (coord N14), ADC_DATA_RDY */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_DATA_RDY_PERIPHERAL                             GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_DATA_RDY_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADC_DATA_RDY_CHANNEL                                  13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADC_DATA_RDY_GPIO                                   GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADC_DATA_RDY_GPIO_PIN                                 13U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADC_DATA_RDY_GPIO_PIN_MASK                    (1U << 13U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_19 (coord U2), ENET_RGMII_MDC */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_MDC_PERIPHERAL                          ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_MDC_SIGNAL                              enet_mdc   /*!< Signal name */

/* GPIO_EMC_B2_00 (coord K2), SEMC_D16/U25[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SCK_PERIPHERAL                              LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SCK_SIGNAL                                     SCK   /*!< Signal name */

/* GPIO_EMC_B2_01 (coord K4), SEMC_D17/U25[4] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_PCS0_PERIPHERAL                             LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_PCS0_SIGNAL                                   PCS0   /*!< Signal name */

/* GPIO_EMC_B2_02 (coord K3), SEMC_D18/U25[5] */
/* Routed pin properties */
#define BOARD_INITPINS_BG95_PWRKEY_PERIPHERAL                              GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_BG95_PWRKEY_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BG95_PWRKEY_CHANNEL                                   12U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BG95_PWRKEY_GPIO                                    GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BG95_PWRKEY_GPIO_PIN                                  12U   /*!< GPIO pin number */
#define BOARD_INITPINS_BG95_PWRKEY_GPIO_PIN_MASK                     (1U << 12U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_03 (coord R1), SEMC_D19/U25[7] */
/* Routed pin properties */
#define BOARD_INITPINS_BG95_RESET_PERIPHERAL                               GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_BG95_RESET_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BG95_RESET_CHANNEL                                    13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BG95_RESET_GPIO                                     GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BG95_RESET_GPIO_PIN                                   13U   /*!< GPIO pin number */
#define BOARD_INITPINS_BG95_RESET_GPIO_PIN_MASK                      (1U << 13U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_04 (coord M1), SEMC_D20/U25[8] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_TXD2_PERIPHERAL                           ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_TXD2_SIGNAL                            enet_tdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_1G_TXD2_CHANNEL                                   2U   /*!< Signal channel */

/* GPIO_EMC_B2_05 (coord N1), SEMC_D21/U25[10] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_RX_CLK_PERIPHERAL                         ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_RX_CLK_SIGNAL                         enet_rx_clk   /*!< Signal name */

/* GPIO_EMC_B2_06 (coord T1), SEMC_D22/U25[11] */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO8_IO16_PERIPHERAL                               GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO8_IO16_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_GPIO8_IO16_CHANNEL                                    16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GPIO8_IO16_GPIO                                     GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_GPIO8_IO16_GPIO_PIN                                   16U   /*!< GPIO pin number */
#define BOARD_INITPINS_GPIO8_IO16_GPIO_PIN_MASK                      (1U << 16U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_07 (coord M3), SEMC_D23/U25[13] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_RXD3_PERIPHERAL                           ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_RXD3_SIGNAL                            enet_rdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_1G_RXD3_CHANNEL                                   3U   /*!< Signal channel */

/* GPIO_EMC_B2_08 (coord P1), SEMC_DM2/U25[15] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_RXD2_PERIPHERAL                           ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_RXD2_SIGNAL                            enet_rdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_1G_RXD2_CHANNEL                                   2U   /*!< Signal channel */

/* GPIO_EMC_B2_09 (coord N2), USER_LED_1 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_LED_1_PERIPHERAL                               GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_USER_LED_1_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_LED_1_CHANNEL                                    19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_LED_1_GPIO                                     GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_LED_1_GPIO_PIN                                   19U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_LED_1_GPIO_PIN_MASK                      (1U << 19U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_10 (coord R2), USER_LED_2 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_LED_2_PERIPHERAL                               GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_USER_LED_2_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_LED_2_CHANNEL                                    20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_LED_2_GPIO                                     GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_LED_2_GPIO_PIN                                   20U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_LED_2_GPIO_PIN_MASK                      (1U << 20U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_11 (coord L4), SEMC_D26/U25[45] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_TXD0_PERIPHERAL                           ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_TXD0_SIGNAL                            enet_tdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_1G_TXD0_CHANNEL                                   0U   /*!< Signal channel */

/* GPIO_EMC_B2_12 (coord M2), SEMC_D27/U25[47] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_TXD1_PERIPHERAL                           ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_TXD1_SIGNAL                            enet_tdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_1G_TXD1_CHANNEL                                   1U   /*!< Signal channel */

/* GPIO_EMC_B2_13 (coord K5), SEMC_D28/U25[48] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_TX_EN_PERIPHERAL                          ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_TX_EN_SIGNAL                           enet_tx_en   /*!< Signal name */

/* GPIO_EMC_B2_14 (coord M4), SEMC_D29/U25[50] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_CLKIO_PERIPHERAL                          ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_CLKIO_SIGNAL                       enet_tx_clk_io   /*!< Signal name */

/* GPIO_EMC_B2_15 (coord L2), SEMC_D30/U25[51] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_RXD0_PERIPHERAL                           ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_RXD0_SIGNAL                            enet_rdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_1G_RXD0_CHANNEL                                   0U   /*!< Signal channel */

/* GPIO_EMC_B2_16 (coord P2), SEMC_D31/U25[53] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_RXD1_PERIPHERAL                           ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_RXD1_SIGNAL                            enet_rdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_1G_RXD1_CHANNEL                                   1U   /*!< Signal channel */

/* GPIO_EMC_B2_17 (coord T2), SEMC_DM3/U25[39] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_RX_EN_PERIPHERAL                          ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_RX_EN_SIGNAL                           enet_rx_en   /*!< Signal name */

/* GPIO_EMC_B2_18 (coord N3), SEMC_DQS4 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_BUTTON_PERIPHERAL                              GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_USER_BUTTON_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_BUTTON_CHANNEL                                   28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_BUTTON_GPIO                                    GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_BUTTON_GPIO_PIN                                  28U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_BUTTON_GPIO_PIN_MASK                     (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_20 (coord R3), ENET_RGMII_MDIO */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_MDIO_PERIPHERAL                           ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_MDIO_SIGNAL                             enet_mdio   /*!< Signal name */

/* GPIO_SD_B2_00 (coord J15), FlexSPI_B_D3/U21[E1] */
/* Routed pin properties */
#define BOARD_INITPINS_SDHC2_DATA3_PERIPHERAL                             USDHC2   /*!< Peripheral name */
#define BOARD_INITPINS_SDHC2_DATA3_SIGNAL                             usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SDHC2_DATA3_CHANNEL                                    3U   /*!< Signal channel */

/* GPIO_SD_B2_01 (coord J14), FlexSPI_B_D2/U21[E2] */
/* Routed pin properties */
#define BOARD_INITPINS_SDHC2_DATA2_PERIPHERAL                             USDHC2   /*!< Peripheral name */
#define BOARD_INITPINS_SDHC2_DATA2_SIGNAL                             usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SDHC2_DATA2_CHANNEL                                    2U   /*!< Signal channel */

/* GPIO_SD_B2_02 (coord H13), FlexSPI_B_D1/U21[E3] */
/* Routed pin properties */
#define BOARD_INITPINS_SDHC2_DATA1_PERIPHERAL                             USDHC2   /*!< Peripheral name */
#define BOARD_INITPINS_SDHC2_DATA1_SIGNAL                             usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SDHC2_DATA1_CHANNEL                                    1U   /*!< Signal channel */

/* GPIO_SD_B2_03 (coord E15), FlexSPI_B_D0/U21[D5] */
/* Routed pin properties */
#define BOARD_INITPINS_SDHC2_DATA0_PERIPHERAL                             USDHC2   /*!< Peripheral name */
#define BOARD_INITPINS_SDHC2_DATA0_SIGNAL                             usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SDHC2_DATA0_CHANNEL                                    0U   /*!< Signal channel */

/* GPIO_SD_B2_04 (coord F14), FlexSPI_B_CLK/U21[B1] */
/* Routed pin properties */
#define BOARD_INITPINS_SDHC2_CLK_PERIPHERAL                               USDHC2   /*!< Peripheral name */
#define BOARD_INITPINS_SDHC2_CLK_SIGNAL                                usdhc_clk   /*!< Signal name */

/* GPIO_SD_B2_06 (coord F17), FlexSPI_A_SS0/U23[1]/U21[C2] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_TXD3_PERIPHERAL                           ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_TXD3_SIGNAL                            enet_tdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_1G_TXD3_CHANNEL                                   3U   /*!< Signal channel */

/* GPIO_SD_B2_07 (coord G14), FlexSPI_A_CLK/U23[6]/U21[B2] */
/* Routed pin properties */
#define BOARD_INITPINS_DIG_IN_1_PERIPHERAL                                GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_DIG_IN_1_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DIG_IN_1_CHANNEL                                      16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIG_IN_1_GPIO                                      GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DIG_IN_1_GPIO_PIN                                     16U   /*!< GPIO pin number */
#define BOARD_INITPINS_DIG_IN_1_GPIO_PIN_MASK                        (1U << 16U)   /*!< GPIO pin mask */

/* GPIO_SD_B2_08 (coord F15), FlexSPI_A_D0/U23[5]/U21[D3] */
/* Routed pin properties */
#define BOARD_INITPINS_DIG_IN_2_PERIPHERAL                                GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_DIG_IN_2_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DIG_IN_2_CHANNEL                                      17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIG_IN_2_GPIO                                      GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DIG_IN_2_GPIO_PIN                                     17U   /*!< GPIO pin number */
#define BOARD_INITPINS_DIG_IN_2_GPIO_PIN_MASK                        (1U << 17U)   /*!< GPIO pin mask */

/* GPIO_SD_B2_09 (coord H15), FlexSPI_A_D1/U23[2]/U21[D2] */
/* Routed pin properties */
#define BOARD_INITPINS_DIG_IN_3_PERIPHERAL                                GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_DIG_IN_3_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DIG_IN_3_CHANNEL                                      18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIG_IN_3_GPIO                                      GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DIG_IN_3_GPIO_PIN                                     18U   /*!< GPIO pin number */
#define BOARD_INITPINS_DIG_IN_3_GPIO_PIN_MASK                        (1U << 18U)   /*!< GPIO pin mask */

/* GPIO_SD_B2_10 (coord H14), FlexSPI_A_D2/U23[3]/U21[C4] */
/* Routed pin properties */
#define BOARD_INITPINS_DIG_IN_4_PERIPHERAL                                GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_DIG_IN_4_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DIG_IN_4_CHANNEL                                      19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIG_IN_4_GPIO                                      GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DIG_IN_4_GPIO_PIN                                     19U   /*!< GPIO pin number */
#define BOARD_INITPINS_DIG_IN_4_GPIO_PIN_MASK                        (1U << 19U)   /*!< GPIO pin mask */

/* GPIO_SD_B2_11 (coord F16), FlexSPI_A_D3/U23[7]/U21[D4] */
/* Routed pin properties */
#define BOARD_INITPINS_RESET_ETH_PERIPHERAL                               GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_RESET_ETH_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RESET_ETH_CHANNEL                                     20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RESET_ETH_GPIO                                     GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RESET_ETH_GPIO_PIN                                    20U   /*!< GPIO pin number */
#define BOARD_INITPINS_RESET_ETH_GPIO_PIN_MASK                       (1U << 20U)   /*!< GPIO pin mask */

/* GPIO_AD_15 (coord M14), SPDIF_IN/U43[4]/BT_RST#/U16[14]/J54[54] */
/* Routed pin properties */
#define BOARD_INITPINS_DSI_LPTE_PERIPHERAL                                 GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_DSI_LPTE_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DSI_LPTE_CHANNEL                                      14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSI_LPTE_GPIO                                       GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DSI_LPTE_GPIO_PIN                                     14U   /*!< GPIO pin number */
#define BOARD_INITPINS_DSI_LPTE_GPIO_PIN_MASK                        (1U << 14U)   /*!< GPIO pin mask */

/* GPIO_AD_16 (coord N17), SPDIF_OUT/WIFI_RST_B/U354[3] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_1G_MDC_PERIPHERAL                            ENET_1G   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_1G_MDC_SIGNAL                               enet_mdc   /*!< Signal name */

/* GPIO_AD_26 (coord L14), CSI_PWR_CTL/USER_LED_CTL2/J50[16] */
/* Routed pin properties */
#define BOARD_INITPINS_PWM2_A1_PERIPHERAL                                   PWM2   /*!< Peripheral name */
#define BOARD_INITPINS_PWM2_A1_SIGNAL                                          A   /*!< Signal name */
#define BOARD_INITPINS_PWM2_A1_CHANNEL                                        1U   /*!< Signal channel */

/* GPIO_AD_28 (coord L17), LPSPI1_SCK/U27[6]/BT_DEV_WAKE/U354[9]/U16[39]/J10[12] */
/* Routed pin properties */
#define BOARD_INITPINS_PWM2_A2_PERIPHERAL                                   PWM2   /*!< Peripheral name */
#define BOARD_INITPINS_PWM2_A2_SIGNAL                                          A   /*!< Signal name */
#define BOARD_INITPINS_PWM2_A2_CHANNEL                                        2U   /*!< Signal channel */

/* GPIO_AD_27 (coord N16), BT_HOST_WAKE/U16[38]/BT_WAKE_B_3V3/J54[20] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_MDIO_PERIPHERAL                         ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_MDIO_SIGNAL                            enet_mdio   /*!< Signal name */

/* GPIO_AD_29 (coord M17), LPSPI1_PCS0/U27[1]/J10[6]/J10[3]/WL_HOST_WAKE/U16[27]/WIFI_WAKE_B_3V3/U355[21] */
/* Routed pin properties */
#define BOARD_INITPINS_WLAN_PD_PERIPHERAL                                  GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_WLAN_PD_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_WLAN_PD_CHANNEL                                       28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_WLAN_PD_GPIO                                        GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_WLAN_PD_GPIO_PIN                                      28U   /*!< GPIO pin number */
#define BOARD_INITPINS_WLAN_PD_GPIO_PIN_MASK                         (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_DISP_B1_00 (coord E13), ENET_RGMII_RX_EN/U10[26] */
/* Routed pin properties */
#define BOARD_INITPINS_IRQ_PE_PERIPHERAL                                  GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_IRQ_PE_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_IRQ_PE_CHANNEL                                        21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IRQ_PE_GPIO                                        GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_IRQ_PE_GPIO_PIN                                       21U   /*!< GPIO pin number */
#define BOARD_INITPINS_IRQ_PE_GPIO_PIN_MASK                          (1U << 21U)   /*!< GPIO pin mask */

/* GPIO_DISP_B1_02 (coord D11), ENET_RGMII_RXD0/U10[25] */
/* Routed pin properties */
#define BOARD_INITPINS_DSI_CTP_IRQ_PERIPHERAL                             GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_DSI_CTP_IRQ_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DSI_CTP_IRQ_CHANNEL                                   23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSI_CTP_IRQ_GPIO                                   GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DSI_CTP_IRQ_GPIO_PIN                                  23U   /*!< GPIO pin number */
#define BOARD_INITPINS_DSI_CTP_IRQ_GPIO_PIN_MASK                     (1U << 23U)   /*!< GPIO pin mask */

/* GPIO_DISP_B1_03 (coord E11), ENET_RGMII_RXD1/U10[24] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_INT_PERIPHERAL                                 GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_INT_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADC_INT_CHANNEL                                       24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADC_INT_GPIO                                       GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADC_INT_GPIO_PIN                                      24U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADC_INT_GPIO_PIN_MASK                         (1U << 24U)   /*!< GPIO pin mask */

/* GPIO_DISP_B1_08 (coord A15), ENET_RGMII_TXD1/U10[17]/BT_CFG[2] */
/* Routed pin properties */
#define BOARD_INITPINS_BOOTCFG_2_PERIPHERAL                               GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_BOOTCFG_2_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BOOTCFG_2_CHANNEL                                     29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BOOTCFG_2_GPIO                                     GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BOOTCFG_2_GPIO_PIN                                    29U   /*!< GPIO pin number */
#define BOARD_INITPINS_BOOTCFG_2_GPIO_PIN_MASK                       (1U << 29U)   /*!< GPIO pin mask */

/* GPIO_DISP_B1_09 (coord C13), ENET_RGMII_TXD0/U10[18]/BT_CFG[3] */
/* Routed pin properties */
#define BOARD_INITPINS_BOOTCFG_3_PERIPHERAL                               GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_BOOTCFG_3_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BOOTCFG_3_CHANNEL                                     30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BOOTCFG_3_GPIO                                     GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BOOTCFG_3_GPIO_PIN                                    30U   /*!< GPIO pin number */
#define BOARD_INITPINS_BOOTCFG_3_GPIO_PIN_MASK                       (1U << 30U)   /*!< GPIO pin mask */

/* GPIO_DISP_B1_10 (coord B14), ENET_RGMII_TX_EN/U10[19]/BT_CFG[4] */
/* Routed pin properties */
#define BOARD_INITPINS_BOOTCFG_4_PERIPHERAL                               GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_BOOTCFG_4_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BOOTCFG_4_CHANNEL                                     31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BOOTCFG_4_GPIO                                     GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BOOTCFG_4_GPIO_PIN                                    31U   /*!< GPIO pin number */
#define BOARD_INITPINS_BOOTCFG_4_GPIO_PIN_MASK                       (1U << 31U)   /*!< GPIO pin mask */

/* GPIO_DISP_B1_11 (coord A14), ENET_RGMII_TXC/U10[20]/BT_CFG[5] */
/* Routed pin properties */
#define BOARD_INITPINS_BOOTCFG_5_PERIPHERAL                               GPIO11   /*!< Peripheral name */
#define BOARD_INITPINS_BOOTCFG_5_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BOOTCFG_5_CHANNEL                                      0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BOOTCFG_5_GPIO                                     GPIO11   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BOOTCFG_5_GPIO_PIN                                     0U   /*!< GPIO pin number */
#define BOARD_INITPINS_BOOTCFG_5_GPIO_PIN_MASK                        (1U << 0U)   /*!< GPIO pin mask */

/* GPIO_DISP_B2_02 (coord E9), ENET_TXD0/U7[24]/BT_CFG[8] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_TXD0_PERIPHERAL                         ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_TXD0_SIGNAL                           enet_tdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_QOS_TXD0_CHANNEL                                  0U   /*!< Signal channel */

/* GPIO_DISP_B2_03 (coord D7), ENET_TXD1/U7[25]/BT_CFG[9] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_TXD1_PERIPHERAL                         ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_TXD1_SIGNAL                           enet_tdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_QOS_TXD1_CHANNEL                                  1U   /*!< Signal channel */

/* GPIO_DISP_B2_04 (coord C7), ENET_TXEN/U7[23]/BT_CFG[10] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_TX_EN_PERIPHERAL                        ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_TX_EN_SIGNAL                          enet_tx_en   /*!< Signal name */

/* GPIO_DISP_B2_05 (coord C9), ENET_TX_REF_CLK/U7[9]/BT_CFG[11] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_TXCLK_PERIPHERAL                        ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_TXCLK_SIGNAL                         enet_tx_clk   /*!< Signal name */

/* GPIO_DISP_B2_06 (coord C6), ENET_RXD0/U7[16] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_RXD0_PERIPHERAL                         ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_RXD0_SIGNAL                           enet_rdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_QOS_RXD0_CHANNEL                                  0U   /*!< Signal channel */

/* GPIO_DISP_B2_07 (coord D6), ENET_RXD1/U7[15] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_RXD1_PERIPHERAL                         ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_RXD1_SIGNAL                           enet_rdata   /*!< Signal name */
#define BOARD_INITPINS_ENET_QOS_RXD1_CHANNEL                                  1U   /*!< Signal channel */

/* GPIO_DISP_B2_08 (coord B5), ENET_CRS_DV/U7[18] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_QOS_RX_EN_PERIPHERAL                        ENET_QOS   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_QOS_RX_EN_SIGNAL                          enet_rx_en   /*!< Signal name */

/* GPIO_DISP_B2_09 (coord D8), ENET_RXER/U7[20] */
/* Routed pin properties */
#define BOARD_INITPINS_BT_PD_PERIPHERAL                                   GPIO11   /*!< Peripheral name */
#define BOARD_INITPINS_BT_PD_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BT_PD_CHANNEL                                         10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BT_PD_GPIO                                         GPIO11   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BT_PD_GPIO_PIN                                        10U   /*!< GPIO pin number */
#define BOARD_INITPINS_BT_PD_GPIO_PIN_MASK                           (1U << 10U)   /*!< GPIO pin mask */

/* GPIO_DISP_B2_10 (coord D9), LPUART2_TXD/BT_UART_TXD/U354[4]/U16[2]/J25[3]/J9[4] */
/* Routed pin properties */
#define BOARD_INITPINS_LPI2C3_SCL_PERIPHERAL                              LPI2C3   /*!< Peripheral name */
#define BOARD_INITPINS_LPI2C3_SCL_SIGNAL                                     SCL   /*!< Signal name */

/* GPIO_DISP_B2_11 (coord A6), LPUART2_RXD/BT_UART_RXD/U16[3]/U355[20]/J9[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPI2C3_SDA_PERIPHERAL                              LPI2C3   /*!< Peripheral name */
#define BOARD_INITPINS_LPI2C3_SDA_SIGNAL                                     SDA   /*!< Signal name */

/* GPIO_DISP_B2_12 (coord B6), RGMII1_PHY_INTB/U10[31]/BT_UART_CTS/U16[5]/U355[19]/J9[6] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI4_SCK_PERIPHERAL                              LPSPI4   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI4_SCK_SIGNAL                                     SCK   /*!< Signal name */

/* GPIO_DISP_B2_13 (coord A5), INT1_COMBO/BT_UART_RTS/U16[4]/U354[5]/ETHPHY_RST_B/U10[12] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI4_SIN_PERIPHERAL                              LPSPI4   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI4_SIN_SIGNAL                                     SIN   /*!< Signal name */

/* GPIO_DISP_B2_14 (coord A7), INT2_COMBO/CSI_RST_B */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI4_SOUT_PERIPHERAL                             LPSPI4   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI4_SOUT_SIGNAL                                   SOUT   /*!< Signal name */

/* GPIO_DISP_B2_15 (coord A4), WDOG_B/LCM_PWR_EN/J48[32] */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI4_PCS0_PERIPHERAL                             LPSPI4   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI4_PCS0_SIGNAL                                   PCS0   /*!< Signal name */

/* GPIO_LPSR_02 (coord P6), BOOT_MODE[0] */
/* Routed pin properties */
#define BOARD_INITPINS_BOOTMODE_1_PERIPHERAL                              GPIO12   /*!< Peripheral name */
#define BOARD_INITPINS_BOOTMODE_1_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BOOTMODE_1_CHANNEL                                     2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BOOTMODE_1_GPIO                                    GPIO12   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BOOTMODE_1_GPIO_PIN                                    2U   /*!< GPIO pin number */
#define BOARD_INITPINS_BOOTMODE_1_GPIO_PIN_MASK                       (1U << 2U)   /*!< GPIO pin mask */

/* GPIO_LPSR_03 (coord T7), BOOT_MODE[1] */
/* Routed pin properties */
#define BOARD_INITPINS_BOOTMODE_0_PERIPHERAL                              GPIO12   /*!< Peripheral name */
#define BOARD_INITPINS_BOOTMODE_0_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BOOTMODE_0_CHANNEL                                     3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BOOTMODE_0_GPIO                                    GPIO12   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BOOTMODE_0_GPIO_PIN                                    3U   /*!< GPIO pin number */
#define BOARD_INITPINS_BOOTMODE_0_GPIO_PIN_MASK                       (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_LPSR_08 (coord U8), DMIC_CLK/U41[1]/U44[1]/J50[18] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART11_TXD_PERIPHERAL                          LPUART11   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART11_TXD_SIGNAL                                   TXD   /*!< Signal name */

/* GPIO_LPSR_09 (coord P5), DMIC_DATA0/U41[5]/J50[20]/LPSPI6_CS0/J26[11] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART11_RXD_PERIPHERAL                          LPUART11   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART11_RXD_SIGNAL                                   RXD   /*!< Signal name */

/* GPIO_LPSR_05 (coord N8), I2C5_SCL/J48[27]/U32[17]/U34[4]/J10[20] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C5_SCL_PERIPHERAL                                LPI2C5   /*!< Peripheral name */
#define BOARD_INITPINS_I2C5_SCL_SIGNAL                                       SCL   /*!< Signal name */

/* GPIO_LPSR_04 (coord N7), I2C5_SDA/J48[26]/U32[18]/U34[6]/J10[18] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C5_SDA_PERIPHERAL                                LPI2C5   /*!< Peripheral name */
#define BOARD_INITPINS_I2C5_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_EMC_B1_40 (coord K1), SEMC_RDY/U14A[C8] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART6_TXD_PERIPHERAL                            LPUART6   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART6_TXD_SIGNAL                                    TXD   /*!< Signal name */

/* GPIO_EMC_B1_41 (coord L1), SEMC_CSX0/U14A[C6] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART6_RXD_PERIPHERAL                            LPUART6   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART6_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_21 (coord K14), SAI1_TXD[0]/J9[9]/J62[1]/BT_PCM_TXD/U16[9]/U354[6] */
/* Routed pin properties */
#define BOARD_INITPINS_BT_PCM_TXD_PERIPHERAL                            FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_BT_PCM_TXD_SIGNAL                         FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_AD_22 (coord K12), SAI1_TX_BCLK/J9[11]/BT_PCM_BCLK/U16[11]/U354[7]/U355[17] */
/* Routed pin properties */
#define BOARD_INITPINS_BT_PCM_BCLK_PERIPHERAL                           FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_BT_PCM_BCLK_SIGNAL                        FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_AD_23 (coord J12), SAI1_TX_SYNC/J9[13]/BT_PCM_SYNC/U16[8]/U354[8]/U355[16] */
/* Routed pin properties */
#define BOARD_INITPINS_BT_PCM_SYNC_PERIPHERAL                           FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_BT_PCM_SYNC_SIGNAL                        FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_AD_04 (coord M13), RS485_UART_CTS / BLUETOOTH_UART_CTS */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART8_CTS_PERIPHERAL                              GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART8_CTS_SIGNAL                            gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_LPUART8_CTS_CHANNEL                                    3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LPUART8_CTS_GPIO                                    GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LPUART8_CTS_GPIO_PIN                                   3U   /*!< GPIO pin number */
#define BOARD_INITPINS_LPUART8_CTS_GPIO_PIN_MASK                      (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_AD_05 (coord P13), RS485_UART_RTS / BLUETOOTH_UART_RTS */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART8_RTS_PERIPHERAL                              GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART8_RTS_SIGNAL                            gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_LPUART8_RTS_CHANNEL                                    4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LPUART8_RTS_GPIO                                    GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LPUART8_RTS_GPIO_PIN                                   4U   /*!< GPIO pin number */
#define BOARD_INITPINS_LPUART8_RTS_GPIO_PIN_MASK                      (1U << 4U)   /*!< GPIO pin mask */

/* GPIO_AD_10 (coord R17), USB_OTG1_PWR/J26[2]/U26[A1] */
/* Routed pin properties */
#define BOARD_INITPINS_USB1_PWR_PERIPHERAL                                 GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_USB1_PWR_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USB1_PWR_CHANNEL                                       9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USB1_PWR_GPIO                                       GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USB1_PWR_GPIO_PIN                                      9U   /*!< GPIO pin number */
#define BOARD_INITPINS_USB1_PWR_GPIO_PIN_MASK                         (1U << 9U)   /*!< GPIO pin mask */

/* GPIO_AD_35 (coord G17), 1588_EVENT0_OUT/SD_PWREN_B */
/* Routed pin properties */
#define BOARD_INITPINS_SDHC1_RESET_N_PERIPHERAL                           GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_SDHC1_RESET_N_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SDHC1_RESET_N_CHANNEL                                  2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SDHC1_RESET_N_GPIO                                 GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SDHC1_RESET_N_GPIO_PIN                                 2U   /*!< GPIO pin number */
#define BOARD_INITPINS_SDHC1_RESET_N_GPIO_PIN_MASK                    (1U << 2U)   /*!< GPIO pin mask */

/* GPIO_AD_32 (coord K16), ENET_MDC/U7[12]/SD1_CD_B/J15[9] */
/* Routed pin properties */
#define BOARD_INITPINS_SDHC1_CD_N_PERIPHERAL                           CM7_GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_SDHC1_CD_N_SIGNAL                         gpio_mux_io_cm7   /*!< Signal name */
#define BOARD_INITPINS_SDHC1_CD_N_CHANNEL                                    31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SDHC1_CD_N_GPIO                                 CM7_GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SDHC1_CD_N_GPIO_PIN                                   31U   /*!< GPIO pin number */
#define BOARD_INITPINS_SDHC1_CD_N_GPIO_PIN_MASK                      (1U << 31U)   /*!< GPIO pin mask */

/* MIPI_DSI_DP1 (coord B10), MIPI_DSI_DP1/J48[9] */
/* Routed pin properties */
#define BOARD_INITPINS_MIPI_DSI_DP1_PERIPHERAL                          DSI_HOST   /*!< Peripheral name */
#define BOARD_INITPINS_MIPI_DSI_DP1_SIGNAL                                    DP   /*!< Signal name */
#define BOARD_INITPINS_MIPI_DSI_DP1_CHANNEL                                   1U   /*!< Signal channel */

/* MIPI_DSI_DN1 (coord A10), MIPI_DSI_DN1/J48[8] */
/* Routed pin properties */
#define BOARD_INITPINS_MIPI_DSI_DN1_PERIPHERAL                          DSI_HOST   /*!< Peripheral name */
#define BOARD_INITPINS_MIPI_DSI_DN1_SIGNAL                                    DN   /*!< Signal name */
#define BOARD_INITPINS_MIPI_DSI_DN1_CHANNEL                                   1U   /*!< Signal channel */

/* MIPI_DSI_CKP (coord B9), MIPI_DSI_CLKP/J48[12] */
/* Routed pin properties */
#define BOARD_INITPINS_MIPI_DSI_CLKP_PERIPHERAL                         DSI_HOST   /*!< Peripheral name */
#define BOARD_INITPINS_MIPI_DSI_CLKP_SIGNAL                                 CLKP   /*!< Signal name */

/* MIPI_DSI_CKN (coord A9), MIPI_DSI_CLKN/J48[11] */
/* Routed pin properties */
#define BOARD_INITPINS_MIPI_DSI_CLKN_PERIPHERAL                         DSI_HOST   /*!< Peripheral name */
#define BOARD_INITPINS_MIPI_DSI_CLKN_SIGNAL                                 CLKN   /*!< Signal name */

/* MIPI_DSI_DP0 (coord B8), MIPI_DSI_DP0/J48[6] */
/* Routed pin properties */
#define BOARD_INITPINS_MIPI_DSI_DP0_PERIPHERAL                          DSI_HOST   /*!< Peripheral name */
#define BOARD_INITPINS_MIPI_DSI_DP0_SIGNAL                                    DP   /*!< Signal name */
#define BOARD_INITPINS_MIPI_DSI_DP0_CHANNEL                                   0U   /*!< Signal channel */

/* MIPI_DSI_DN0 (coord A8), MIPI_DSI_DN0/J48[5] */
/* Routed pin properties */
#define BOARD_INITPINS_MIPI_DSI_DN0_PERIPHERAL                          DSI_HOST   /*!< Peripheral name */
#define BOARD_INITPINS_MIPI_DSI_DN0_SIGNAL                                    DN   /*!< Signal name */
#define BOARD_INITPINS_MIPI_DSI_DN0_CHANNEL                                   0U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
