@echo off
rem # ************************************************************************
rem # SPDX-License-Identifier: BSD-3-Clause
rem # Copyright (c) 2021 - 2023 TQ-Systems GmbH <license@tq-group.com>,
rem # D-82229 Seefeld, Germany.
rem # Author: Maximilian Kürth
rem # Description: Script for generating version header based on information
rem # from VCS
rem #*************************************************************************

set FILENAME=version.h
set FILE=%FILENAME%
set TMP=%TEMP%\%FILENAME%

for /F %%i in ('"git describe --match "*BSP.*" --abbrev=0 --tags HEAD"') do set VERSION=%%i
for /F %%i in ('git branch --show-current') do set BRANCH=%%i

(
  echo //*****************************************************************************
  echo /*!
  echo  * \file  %FILENAME%
  echo  * \brief Auto generated version information file.
  echo  * \note  Do not edit this file.
  echo  */
  echo //*****************************************************************************
  echo.
  echo #ifndef VERSION_H
  echo #define VERSION_H
  echo.
  echo ///! Defines the plain version string.
  echo #define VERSION "%VERSION%"
  echo ///! Defines the current branch in VCS.
  echo #define BRANCH  "%BRANCH%"
  echo.
  echo #endif
) > %TMP%

FC %TMP% %FILE% > nul
if %errorlevel% == 0 goto nodiff

copy /Y %TMP% %FILE%

:nodiff
del %TMP%
